house:
  address: {number: 34, street: Main Street}
  family:
    name: Doe
    parents: [John, Jane]
house:
  address: {number: 34, street: Main Street}
  family:
    name: Doe
    parents: [John, Jane]
house:
  address: {number: 34, street: Main Street}
  family:
    name: Doe
    parents: [John, Jane]
